USE Hotel

--Insert some example values in the PACKAGES table

INSERT INTO PACKAGES VALUES ('RO',0);
INSERT INTO PACKAGES VALUES ('BB',5);
INSERT INTO PACKAGES VALUES ('HB',10);
INSERT INTO PACKAGES VALUES ('FB',15);
INSERT INTO PACKAGES VALUES ('AI',20);
SELECT * FROM PACKAGES